### ISSUE TITLE
go.tampa.dev/mentorship link is broken

### ISSUE THREAD

**Issue by ebanner** [TampaDevs/tampadevs-original-site#158]
I'm not sure where the go links are defined these days, but the mentorship link `go.tampa.dev/mentorship` seems to be broken.

I came to it from the pinned slack post in the `#mentorship-program` slack channel:

> https://tampa-devs.slack.com/archives/C051HUUJPEC/p1709909660532429

The link seems like it should be:

> https://my.togetherplatform.com/signup/mixed?organizationId=JwTXjoJx1LtVOn2cjkjE

as defined in this file:

> https://github.com/TampaDevs/go.tampa.dev-v1/blob/57d28507cbe1e2d9542e61e4b08a70d59aec6b97/_redirects#L27

Though that repo seems to be not used anymore.

**Comment by chtzvt** [comment]
Just fixed this— there seems to suddenly be a problem with the regex match pattern I had set up for mentor|mentors|mentorship. 

I’ll do a more thorough set of debugging later, but for now I’ve just configured a static redirect for /mentorship. 

Unfortunately redirect.pizza’s regex matching feature can be a bit finicky, so it’ll take a bit of time and testing to triage before the original set of redirect paths can be restored.

**Comment by chtzvt** [comment]
Very good catch, thanks for the report.

**Comment by chtzvt** [comment]
Specifically, my original matching pattern was `go.tampa.dev/(mentor|mentors|mentorship)(\/.*|$)`. As for why this stopped working, I'm not certain at the moment.
