### ISSUE TITLE
Next event header text is hard to see (?)

### ISSUE THREAD

**Issue by ebanner** [TampaDevs/tampadevs-original-site#167]
This is just a styling critique, but the Next Event header text seems a bit off

![image](https://github.com/TampaDevs/tampadevs/assets/2068912/8317b57f-5a21-4e1d-9a01-53fa2219d56c)

It kind of blends in with the text above and doesn't feel like it's distinguished enough to signal a new section is being started.

If we were to change it to black (or some other color), we would probably also want to change the header text color above to be consistent

![image](https://github.com/TampaDevs/tampadevs/assets/2068912/8bdc54b6-3bbb-4c97-8894-2cc8e10e251e)

**Comment by chtzvt** [comment]
@ebanner Good point-- looks like @manuelosorio fixed this up in his latest PR.

**Comment by ebanner** [comment]
Nice choice on the orange header/black text combo @manuelosorio 👌
