### ISSUE TITLE
Tab favicon (?) is broken on safari

### ISSUE THREAD

**Issue by ebanner** [TampaDevs/tampadevs-original-site#171]
The favicon in the address bar shows fine, but for some reason the favicon (?) in the safari tab is showing a weird image

![image](https://github.com/TampaDevs/tampadevs/assets/2068912/d5e10ebb-b7f7-4914-8d61-541f48a6a17a)

**Comment by manuelosorio** [comment]
It seems that the SVG used for the safari pinned tab was not TampaDevs Icon Logo either. May be worth looking into why it wasn't being rendered properly regardless. 

https://github.com/TampaDevs/tampadevs/blob/1732d24e9461aa7c25bc33b7d644b39067999cfd/src/_assets/img/favicon/safari-pinned-tab.svg
