### ISSUE TITLE
Have SLACK CHAT button on the homepage go straight to slack signup

### ISSUE THREAD

**Issue by ebanner** [TampaDevs/tampadevs-original-site#200]
When I'm at a Tampa Devs event helping people get on the slack, they click the SLACK CHAT button on the page.

![image](https://github.com/TampaDevs/tampadevs/assets/2068912/75d493c4-9e65-4bf3-a2e4-da5848fcba78)

and it brings them down the page and they have to click another button

![image](https://github.com/TampaDevs/tampadevs/assets/2068912/9cf8aebb-eb7a-406f-94ef-5ac3df15e35b)

This results in a kind of awkward two-step experience. I think it would be a lot slicker if the first button just took them directly to the slack sign up link.

Incidentally, when they get brought down the page to the second button, often times that card thing is horizontally cut off on the user's phone, and it's not obvious what to do.

I wasn't able to reproduce this, but it happened last night on two peoples' phones (pretty sure they both had Android phones).

**Comment by chtzvt** [comment]
@ebanner Great idea! I've merged a PR that implements the desired behavior.
