### ISSUE TITLE
FEATURE - Add content for TampaDevs.com/onboarding

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#27]
Blocked by this ticket first: https://github.com/TampaDevs/tampadevs/issues/26

We want to add content for the onboarding process

More notes will come in these comments: here

**Comment by vincentntang** [comment]
feel free to make a google doc as well @haridira and we can add the content later to the site

**Comment by haridira** [comment]
Just noticed this mention (great that ticket #26 has been resolved already!). I will take it from here and update the thread.
