### ISSUE TITLE
FEATURE - Add financial contributors from opencollective and pull it into our home page

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#50]
Use this link provided here:
https://opencollective.com/tampadevs/backers.svg?width=950

and add that image onto our homepage. These are donators to Tampa Devs that will appear on the homepage of the site. Most likely, right below our big name company sponsors

![image](https://user-images.githubusercontent.com/10290348/211679998-8ae6f7cb-6b53-4b07-9ae7-d9cb77a46aec.png)

## Design

In terms of the design of what this might look like, it's open to interpretation. I would check out React Hook Form's readme page to see what it looks like for inspiration

https://github.com/react-hook-form/react-hook-form/blob/master/README.md

and their opencollective page for reference

https://opencollective.com/react-hook-form#backer

**Comment by chtzvt** [comment]
How to do this easily:

```
<a href="https://opencollective.com/tampadevs#backers">
    <img src="https://opencollective.com/tampadevs/backers.svg?width=950" />
</a>
```

Example:

<a href="https://opencollective.com/tampadevs#backers">
    <img src="https://opencollective.com/tampadevs/backers.svg?width=950" />
</a>

**Comment by chtzvt** [comment]
Great implementation by @btruj in #68. Thanks Bryan!

<img width="1070" alt="Screenshot 2023-02-22 at 10 59 51" src="https://user-images.githubusercontent.com/7227500/220681700-f09c09ac-db65-4049-8495-4e9d261c7280.png">
