### ISSUE TITLE
FEATURE - Add github contributors to the home page, below sponsors/financial backers

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#51]
Related to notes here for financial contributors on opencollective https://github.com/TampaDevs/tampadevs/issues/50

We should also add a list of github contributors on the homepage who help build out new features

This will be right below all the sponsors and financial contributors. Here's  an example mockup image from React-Hook-Form

![image](https://user-images.githubusercontent.com/10290348/211681053-1f769cfa-8c40-4a3f-81a8-d930384978e8.png)

Not 100% sure how to pull up the list of github contributors, but github should have some tools for doing this

**Comment by ObieMunoz** [comment]
@vincentntang 
For github, this is very easy @ this endpoint :

https://api.github.com/repos/OWNER/REPO/collaborators

```
curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/collaborators
```

The response data is an array of users, each with login, avatar_url, and other misc. data but I think all needed here is login and avatar.

**Comment by chtzvt** [comment]
@ObieMunoz it's even easier than that!

We can just load an SVG from our OpenCollective page, like so:

```
<img src="https://opencollective.com/tampadevs/contributors.svg?width=890&button=false" />
```

<img src="https://opencollective.com/tampadevs/contributors.svg?width=890&button=false" />

This is how contributors are shown in the [TD organization README](https://github.com/TampaDevs).

**Comment by ObieMunoz** [comment]
@chtzvt that works good if you don't want to link to contributor profiles

edit- nevermind! I'm wrong! seems they are linkable that way too.

That's cool!

**Comment by RyanClementsHax** [comment]
Is this a good issue for a newcomer to help out with? Given this was last touched some time ago, I'm unsure.

Thanks for your time :)

**Comment by chtzvt** [comment]
@RyanClementsHax By all means! I think it’d be a really cool feature :)

**Comment by RyanClementsHax** [comment]
I'm considering contributing but it seems work has been done on this previously and was closed for various reasons.

Is there a source of truth for the specification desired? It seems the previous PRs didn't meet desired criteria.

**Comment by RyanClementsHax** [comment]
It seems like we want something like the following:
- https://github.com/TampaDevs/tampadevs/pull/64#issuecomment-1440489358
- https://github.com/TampaDevs/tampadevs/pull/74#issuecomment-1539242773

But I just want to make sure I understand what is desired before I start working on this.

**Comment by chtzvt** [comment]
Hey @RyanClementsHax! Thanks for your interest-- we really appreciate it 😄 

The goal with displaying the site contributors on the homepage would look similar to what I had outlined in my [issue comment](https://github.com/TampaDevs/tampadevs/pull/64#issuecomment-1407420149) on the first issue you had linked:

![image](https://github.com/TampaDevs/tampadevs/assets/7227500/8dce675f-393c-4111-97d6-7500ac8c7c6d)

A dedicated section for them would be perfect, and well-deserved recognition for these amazing folks' open source work.

**Comment by chtzvt** [comment]
Mobile styling is a bit unfinished 😢

If I recall correctly, the max width is included in the contributors image URL? Just as an idea, we may be able to work around this by generating the parameter on page load.

![image](https://github.com/TampaDevs/tampadevs/assets/7227500/5204b696-726b-4761-8a78-dc1861895b7f)

**Comment by RyanClementsHax** [comment]
Ah good catch. For some reason I thought this was the existing behavior of other pictures on the site so I kept it consistent. My bad.

Initially, I see two options. Do you prefer one of them or do you see another option?

## 1. Center the picture

<img width="339" alt="image" src="https://github.com/TampaDevs/tampadevs/assets/20916810/599893a8-7438-4f0a-81f5-bb9e1ad6e364">

## 2. Dynamically resize

This could run into awkward sizing issues since there [isn't an option to center the avatars](https://docs.opencollective.com/help/collectives/collective-settings/data-export#contributor-image). We could get around this by doing some math on the avatar size relative to the image size.

```html
  <section class="container sponsor-container">
    {# Github contributors #}
    <h3>Contributors</h3>
    <div id="contributors-container" class="sponsor-list sponsor-list__silver">
      <img id="contributors" />
      <div class="sponsor-button-wrapper contributors-cta-container">
        <a class="sponsor-button td-alert-banner" href="https://github.com/TampaDevs/tampadevs">🤝 Become a contributor 🤝</a>
      </div>
    </div>
    <script type="text/javascript">
      window.onload = function() {
        const container = document.querySelector('#contributors-container')
        const img = document.querySelector('img#contributors')
        const paddingLeft = parseInt(window.getComputedStyle(img).getPropertyValue('padding-left').replace("px", ""))
        const paddingRight = parseInt(window.getComputedStyle(img).getPropertyValue('padding-right').replace("px", ""))
        img.src = `https://opencollective.com/tampadevs/contributors.svg?width=${container.clientWidth - paddingLeft - paddingRight}&button=false`
      }
    </script>
  </section>
```

<img width="305" alt="image" src="https://github.com/TampaDevs/tampadevs/assets/20916810/21d905de-9939-4e62-a664-7d172946c954">

**Comment by RyanClementsHax** [comment]
@chtzvt Which would you prefer?

**Comment by chtzvt** [comment]
@RyanClementsHax Would it be possible to both center the picture and scale the image down?

I'm not a huge fan of the second option because it really pushes the bottom section of the site down.

**Comment by RyanClementsHax** [comment]
<img width="368" alt="image" src="https://github.com/TampaDevs/tampadevs/assets/20916810/a1610df5-3669-48c3-960e-779214cd7708">


Something like this @chtzvt ?
