### ISSUE TITLE
[WIP to be refined] - FEATURE - Add more quicklinks on footer

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#66]
![image](https://user-images.githubusercontent.com/10290348/218794197-7ee254ef-69c0-4ad4-b0d8-688b79fa6788.png)

Need to add more quicklinks to the footer. These are based on the redirects we use currently here

[https://github.com/TampaDevs/go.tampa.dev/blob/main/_redirects](https://github.com/TampaDevs/go.tampa.dev/blob/main/_redirects)

This is WIP, more information on this ticket later. Just creating it here to remind myself to refine this ticket further

Things we need quicklinks to

- compresed PDF of the sponsor pitchdeck
- Quick elevator pitch presentations for different contextes

@chtzvt we need to refine mroe notes here later

**Comment by chtzvt** [comment]
We can add this as a dedicated page (/links or something). Probably better than jamming everything in the footer

**Comment by manuelosorio** [comment]
If we want to continue adding more links to the footer, the layout will need to be changed from what we have currently. That could help keep the footer section clean.
