### ISSUE TITLE
Image scaling and alignment are broken on mobile Safari.

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/tampadevs-original-site#69]
It looks like images get stretched on mobile in a way that makes them completely unreadable. This is an issue sitewide for all iOS browsers at minimum:

![905E2EC0-0436-448B-A766-F4BF40D71DC8](https://user-images.githubusercontent.com/7227500/220683757-a87229a7-dae7-41fb-b9c3-1bf06c30e962.png)

![8118AE17-8714-438B-A554-5DCA2BBBB9C6](https://user-images.githubusercontent.com/7227500/220683776-0d623c13-e366-4980-8ea9-c2e5cb0c9dea.png)

Also, there's an issue with image alignment on mobile for the homepage:

![767DA36A-A1B9-4681-8DC9-C66E01AD1A11](https://user-images.githubusercontent.com/7227500/220683738-242661c7-0a21-4a71-8d24-ef0e9edf4a02.png)

**Comment by manuelosorio** [comment]
That's something I can work on.

**Comment by chtzvt** [comment]
@manuelosorio You are incredible by all accounts

**Comment by manuelosorio** [comment]
@chtzvt Do you experience this in any other browser or device?

**Comment by chtzvt** [comment]
@manuelosorio  This seems to happen on any iOS browser (which are all Webkit under the hood). 

I haven't tested on devices with larger viewports than an iPhone 13 Pro, which is the only iOS device I own.

**Comment by manuelosorio** [comment]
Thank for that information that should be help for debugging.

**Comment by manuelosorio** [comment]
Working on the fix now.
