### ISSUE TITLE
FEATURE - Scraped list of events on TampaDevs from meetup.com

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#8]
Basically, write a netlify function that routinely scrapes TampaDevs

Pulls the latest list of events

Publishes it somewhere on the home page

how it's implement and what it looks like though is still undecided.

Not a super high priority feature though, these other features are more important:

- https://github.com/TampaDevs/tampadevs/issues/7 -  CTA speaker
- https://github.com/TampaDevs/tampadevs/issues/4 -> list of sponsors
- https://github.com/TampaDevs/tampadevs/issues/3 -> CTA for sponsors

**Comment by chtzvt** [comment]
Can use CF workers for this

**Comment by chtzvt** [comment]
I'm pleased to announce the availability of an all-new Events API for Tampa Devs and our partner groups: https://events.api.tampa.dev/ ([repo](https://github.com/TampaDevs/events.api.tampa.dev)). 

Now that this is available, we can complete the implementation of this integration. 

Ideally, I'd like to see this available on both https://www.tampadevs.com (for just our events) and https://tampa.dev as well (for the expanded list). 

@manuelosorio @josef-sieber - Would y'all be interested in helping out with this?

**Comment by chtzvt** [comment]
Implemented.
