### ISSUE TITLE
FEATURE - add /privacy-policy placeholder, with links to it on the footer navigation

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#81]
similar to /code-of-conduct, we're also going to implement a /privacy-policy placeholder set of notes
you can basically just copy over the folder structure on code-of-conduct into another folder called `privacy-policy`

AC (acceptance criteria)
- /privacy-policy - add a markdown file here, for the text notations here just put lorem ipsum placeholder on there
- add a link on the footer to this page, similarly to how we handle `/code-of-conduct`

**Comment by sagar1025** [comment]
#86
