### ISSUE TITLE
CONTENT - Add Career Forum Talk Archive into the website, 3/15/23

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#90]
## BACKGROUND

Add this state machine talk from this description here:
https://www.meetup.com/tampadevs/events/290245741/

And the youtube video here: 
https://youtu.be/wgzaE9yrH2Y

## AC (Acceptance criteria)

- Add a new /talk post using the above links, into a blog post on tampadevs.com.

## NOTES

- You can emulate how it's structured here in the app https://www.tampadevs.com/talks/2023/20230201-mobile-development/
- In the repo, this will be under the /talks section

**Comment by adityalochan** [comment]
Working on it

**Comment by adityalochan** [comment]
Please review the PR
