### ISSUE TITLE
Post-Donation Landing Page

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/tampadevs-original-site#97]
A thank-you landing page that we redirect to from OpenCollective post-donation would be ideal, as it would give us better insight into the donation conversion lifecycle. 

https://docs.opencollective.com/help/contributing/development/post-donation-redirect

**Comment by ebanner** [comment]
Hey @chtzvt I'm interested in working on this 👋 

Do you have a sense or preference or idea for what should be on the thank you page and what it should look like? I'm kinda stuck there
