### ISSUE TITLE
Fix New Email Form

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/tampadevs-original-site#98]
I wrote a small service (https://newsletter.api.tampa.dev/signup) to process new newsletter subscriptions and pass them over to SendGrid. 

It's more or less a drop-in replacement and functions properly, but there's no need to actually redirect the user/open a new tab like the form currently does. 

We should override this behavior and just display the status of the newsletter signup on the page (if that's even necessary). 

Also, my signup service can be used on tampa.dev and bayhacks.dev as well. It'll reject other origins, though.

**Comment by chtzvt** [comment]
See https://github.com/TampaDevs/newsletter.api.tampa.dev for the new service

**Comment by vincentntang** [comment]
I think we need to convert this into a javascript form. the default `<form>` element I believe does a redirect

Probably using this blog
https://www.designcise.com/web/tutorial/how-to-convert-html-form-data-to-javascript-object

The other option is to stop the redirect default on HTML form but that might be more work though

@manuelosorio do you wanna give a shot at this?

**Comment by chtzvt** [comment]
Closed by #100
